name: mpnn
dependencies:
        - python=3.7
        - pip
        - rdkit
        - torchvision
        - pytorch
        - openbabel
        - pandas
        - tqdm 
channels:
        - conda-forge
